# Deploy vCenter section
# the following section defines the vCenter / vSphere environment
# were the NSX Manager OVA gets deployed. This can be a separate management vCenter,
# or the same vCenter to which NSX Manager gets registered
deployVcIPAddress: 'vcsa.cpod-velocloud.shwrfr.mooo.com'
deployVcUser: 'administrator@cpod-velocloud.shwrfr.mooo.com'
deployVcPassword: 'VMware1!'

# with NSX 6.2.2 and later you need licnse in order to prepare the hosts
# Uncomment the line below and provide valid license key, otherwise the deployment will fail before preparing the clusters
license_key: 'XXXX-XXXX-XXXX-XXXX'

# NSX Manager OVA deployment parameters
# this section holds all parameters needed to deploy the NSX Manager OVA like IP address, etc.
deployMgmtPortGroup: 'DPortGroup'
deployDataCenterName: "cPod-VELOCLOUD"
deployCluster: 'Cluster'
deployMgmtDatastoreName: 'Datastore'
deployMgmtIpAddress: '172.18.6.4'
deployMgmtDefaultGateway: '172.18.6.1'
deployMgmtNetmask: '255.255.255.0'
deployMgmtDnsServer: '172.18.6.1'
deployMgmtDnsDomain: 'cpod-velocloud.shwrfr.mooo.com'
deployNtpServers: '172.18.6.1'
deploySyslogServer: '172.18.6.1'
deployVmName: 'nsxmanager'
deployHostname: 'nsx.cpod-velocloud.shwrfr.mooo.com'
nsxCliPass: 'VMware1!VMware1!'
nsxEnPass: 'VMware1!VMware1!'

nsxmanOvaPath: 'images'
nsxmanOva: 'VMware-NSX-Manager-6.4.1-8599035.ova'
ovfToolPath: '/usr/bin'  # Use '/Applications' if using ovftool on a MAC

# Target 'register' vCenter section
# the following section defines the vCenter / vSphere environment
# to which NSX Manager will be registered to. This can be the same as deploy vCenter,
# or a separate 'payload' vCenter
vcHostname: "vcsa.cpod-velocloud.shwrfr.mooo.com"
vcIpAddress: "172.18.6.3"
vcUser: "administrator@cpod-velocloud.shwrfr.mooo.com"
vcPassword: "VMware1!"
vcSsoHostname: "vcsa.cpod-velocloud.shwrfr.mooo.com"
vcSsoUser: "administrator@cpod-velocloud.shwrfr.mooo.com"
vcSsoPassword: "VMware1!"

# NSX Manager credentials and RAML file path
nsxmanager_spec:
  raml_file: 'nsxraml/nsxvapi.raml'
  host: "{{ deployMgmtIpAddress }}"
  user: 'admin'
  password: "{{ nsxCliPass }}"

# NSX configuration details
# including controller deployment environment details and IP Pools
nsxControllerPortGroup: 'DPortGroup'
nsxControllerDatastore: 'Datastore'
nsxControllerVcCluster: 'Cluster'
controllerDeployType: 'lab'
controllerPassword: 'VMware1!VMware1!'
controllerSyslogServer: '172.18.6.1'
targetDatacenterName: 'cPod-VELOCLOUD'
targetVdsName: 'DVS'
transportZoneName: 'TZ1'
transportZoneDescription: 'Default TZ'
defaultControllPlaneMode: 'UNICAST_MODE'

nsxIppools:
  controller:
    name: 'controller'
    start_ip: '172.18.6.5'
    end_ip: '172.18.6.7'
    prefix_length: '24'
    gateway: '172.18.6.1'
    dns_server_1: '172.18.6.1'
    dns_server_2: ''
  vteps:
    name: 'vteps'
    start_ip: '172.18.6.8'
    end_ip: '172.18.6.10'
    prefix_length: '24'
    gateway: '172.18.6.1'
    dns_server_1: '172.18.6.1'
    dns_server_2: ''

# ID Pool for VXLAN
segmentIdPoolStart: '5000'
segmentIdPoolEnd: '10000'
mcastEnabled: 'True'
mcastAddrStart: '239.0.0.0'
mcastAddrEnd: '239.255.255.255'
vtep_vlan_id: '0'

# Target vCenter Cluster Section
# the following section defines which clusters in the target vCenter should
# be prepared for NSX (VIB deployment)
targetClusters:
  cluster1:
    clusterName: 'Cluster'

# Lab Config
lab_ls:
  - { name: 'ls_internet' }
  - { name: 'ls_lan_dc1' }
  - { name: 'ls_lan_dc2' }
  - { name: 'ls_lan_bronze' }
  - { name: 'ls_lan_silver1' }
  - { name: 'ls_lan_silver2' }
  - { name: 'ls_lan_silver3' }
  - { name: 'ls_internet1_bronze' }
  - { name: 'ls_internet2_bronze' }
  - { name: 'ls_internet_silver1' }
  - { name: 'ls_internet_silver2' }
  - { name: 'ls_internet_silver3' }
  - { name: 'ls_internet_dc1' }
  - { name: 'ls_internet_dc2' }
  - { name: 'ls_mpls_dc1' }
  - { name: 'ls_mpls_dc2' }
  - { name: 'ls_mpls_silver1' }
  - { name: 'ls_mpls_silver2' }
  - { name: 'ls_mpls_silver3' }
  - { name: 'ls_null' }

internet_edge_interfaces:    
  vnic0: {ip: '172.18.6.250', prefix_len: 24, portgroup_id: "{{ gather_moids_upl_pg.object_id }}", name: 'Uplink vnic', iftype: 'uplink'}
  vnic1: {ip: '20.20.20.1', prefix_len: 24, logical_switch: 'ls_internet', name: 'ls_internet', iftype: 'internal'}
  vnic2: {ip: '20.20.30.1', prefix_len: 24, logical_switch: 'ls_internet1_bronze', name: 'ls_internet1_bronze', iftype: 'internal'}
  vnic3: {ip: '20.20.40.1', prefix_len: 24, logical_switch: 'ls_internet2_bronze', name: 'ls_internet2_bronze', iftype: 'internal'}
  vnic4: {ip: '20.20.50.1', prefix_len: 24, logical_switch: 'ls_internet_silver1', name: 'ls_internet_silver1', iftype: 'internal'}
  vnic5: {ip: '20.20.60.1', prefix_len: 24, logical_switch: 'ls_internet_silver2', name: 'ls_internet_silver2', iftype: 'internal'}
  vnic6: {ip: '20.20.70.1', prefix_len: 24, logical_switch: 'ls_internet_silver3', name: 'ls_internet_silver3', iftype: 'internal'}
  vnic7: {ip: '20.20.80.1', prefix_len: 24, logical_switch: 'ls_internet_dc1', name: 'ls_internet_dc1', iftype: 'internal'}
  vnic8: {ip: '20.20.90.1', prefix_len: 24, logical_switch: 'ls_internet_dc2', name: 'ls_internet_dc2', iftype: 'internal'}
internet_edge_defaultGW: '172.18.6.1'

mpls_edge_interfaces:
  vnic1: {ip: '192.168.10.1', prefix_len: 24, logical_switch: 'ls_mpls_dc1', name: 'ls_mpls_dc1', iftype: 'internal'}
  vnic2: {ip: '192.168.11.1', prefix_len: 24, logical_switch: 'ls_mpls_dc2', name: 'ls_mpls_dc2', iftype: 'internal'}
  vnic3: {ip: '192.168.12.1', prefix_len: 24, logical_switch: 'ls_mpls_silver1', name: 'ls_mpls_silver1', iftype: 'internal'}
  vnic4: {ip: '192.168.13.1', prefix_len: 24, logical_switch: 'ls_mpls_silver2', name: 'ls_mpls_silver2', iftype: 'internal'}
  vnic5: {ip: '192.168.14.1', prefix_len: 24, logical_switch: 'ls_mpls_silver3', name: 'ls_mpls_silver3', iftype: 'internal'}


# VELOCLOUD CONFIGURATION
# VCO Configuration
vco:
  instanceid: vco
  hostname: vco
  username: super@velocloud.net
  password: vcadm!n
  image: 'images/velocloud-vco-3.2.0-GA-20180511.ova'
  ls: 'ls_internet'
  eth0:
    ipAllocationType: 'STATIC'
    ipAddress: '20.20.20.200'
    natipAnsible: '172.18.6.250'
    subnetMask: '255.255.255.0'
    gatewayAddress: '20.20.20.1'
  publickeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQE/9isaw4ToR5GYLm7g6rgLYIZz2c4UdoL4R2DeMypgW1rHv7P0jL3iqR3L+7bY2HggX2DMvdYwXGlKrtoUWY+WhXKiF0tBvH0rWMYR2XZ+s5UiODifkgJ7NEQrOQOwekoHv7l1MmWxI0XVbFYLZ52aMVaQQOljw9SqyMjCAlF2BnXRfSNW86BAF/KiJVhECbvEfrSBH855OGORlXAHtzyTTEpj0zbTHmAzjLKoqTaXjD9IMf38yqDajMa/XwRUKevK+hkvoWCXaKmY+xXy0Csbf4dkNrJBLrEysfRKwKqkxjXJKKBoQ4b+uTGb+x32DPZCphL2ksEx+8oRb/pCKR adeleporte@adeleporte-m01.vmware.com'

vcg1:
  instanceid: vcg1
  hostname: vcg1
  description: vcg1
  password: Velocloud123
  image: 'images/velocloud-vcg-3.2.0-49-R320-20180409-GA.ova'
  ls: 'ls_internet'
  eth0:
    ipAllocationType: 'STATIC'
    ipAddress: '20.20.20.11'
    natipAnsible: '172.18.6.250'
    subnetMask: '255.255.255.0'
    gatewayAddress: '20.20.20.1'
  publickeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQE/9isaw4ToR5GYLm7g6rgLYIZz2c4UdoL4R2DeMypgW1rHv7P0jL3iqR3L+7bY2HggX2DMvdYwXGlKrtoUWY+WhXKiF0tBvH0rWMYR2XZ+s5UiODifkgJ7NEQrOQOwekoHv7l1MmWxI0XVbFYLZ52aMVaQQOljw9SqyMjCAlF2BnXRfSNW86BAF/KiJVhECbvEfrSBH855OGORlXAHtzyTTEpj0zbTHmAzjLKoqTaXjD9IMf38yqDajMa/XwRUKevK+hkvoWCXaKmY+xXy0Csbf4dkNrJBLrEysfRKwKqkxjXJKKBoQ4b+uTGb+x32DPZCphL2ksEx+8oRb/pCKR adeleporte@adeleporte-m01.vmware.com'

vcg2:
  instanceid: vcg2
  hostname: vcg2
  description: vcg2
  password: Velocloud123
  image: 'images/velocloud-vcg-3.2.0-49-R320-20180409-GA.ova'
  ls: 'ls_internet'
  eth0:
    ipAllocationType: 'STATIC'
    ipAddress: '20.20.20.12'
    natipAnsible: '172.18.6.250'
    subnetMask: '255.255.255.0'
    gatewayAddress: '20.20.20.1'
  publickeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQE/9isaw4ToR5GYLm7g6rgLYIZz2c4UdoL4R2DeMypgW1rHv7P0jL3iqR3L+7bY2HggX2DMvdYwXGlKrtoUWY+WhXKiF0tBvH0rWMYR2XZ+s5UiODifkgJ7NEQrOQOwekoHv7l1MmWxI0XVbFYLZ52aMVaQQOljw9SqyMjCAlF2BnXRfSNW86BAF/KiJVhECbvEfrSBH855OGORlXAHtzyTTEpj0zbTHmAzjLKoqTaXjD9IMf38yqDajMa/XwRUKevK+hkvoWCXaKmY+xXy0Csbf4dkNrJBLrEysfRKwKqkxjXJKKBoQ4b+uTGb+x32DPZCphL2ksEx+8oRb/pCKR adeleporte@adeleporte-m01.vmware.com'

vce1:
  instanceid: VCE_BRONZE
  hostname: VCE_BRONZE
  description: VCE_BRONZE
  password: Velocloud123
  image: 'images/edge-VC_VMDK-x86_64-3.2.0-49-R320-20180409-GA-updatable-ext4.ova'
  lat: '50.8503463'
  long: '4.351721099999963'
  lan:
    ipAddress: '10.0.0.1'
  eth0:
    ls: 'ls_lan_bronze'
  eth1:
    ls: 'ls_lan_bronze'
  eth2:
    ipAllocationType: 'STATIC'
    ipAddress: '20.20.30.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '20.20.30.1'
    ls: 'ls_internet1_bronze'
  eth3:
    ipAllocationType: 'STATIC'
    ipAddress: '20.20.40.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '20.20.40.1'
    ls: 'ls_internet2_bronze'
  eth4:
    ls: 'ls_null'
  eth5:
    ls: 'ls_null'
  publickeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQE/9isaw4ToR5GYLm7g6rgLYIZz2c4UdoL4R2DeMypgW1rHv7P0jL3iqR3L+7bY2HggX2DMvdYwXGlKrtoUWY+WhXKiF0tBvH0rWMYR2XZ+s5UiODifkgJ7NEQrOQOwekoHv7l1MmWxI0XVbFYLZ52aMVaQQOljw9SqyMjCAlF2BnXRfSNW86BAF/KiJVhECbvEfrSBH855OGORlXAHtzyTTEpj0zbTHmAzjLKoqTaXjD9IMf38yqDajMa/XwRUKevK+hkvoWCXaKmY+xXy0Csbf4dkNrJBLrEysfRKwKqkxjXJKKBoQ4b+uTGb+x32DPZCphL2ksEx+8oRb/pCKR adeleporte@adeleporte-m01.vmware.com'

vce2:
  instanceid: VCE_SILVER1
  hostname: VCE_SILVER1
  description: VCE_SILVER1
  password: Velocloud123
  image: 'images/edge-VC_VMDK-x86_64-3.2.0-49-R320-20180409-GA-updatable-ext4.ova'
  lat: '48.1351253'
  long: '11.581980499999986'
  lan:
    ipAddress: '10.0.1.1'
  eth0:
    ls: 'ls_lan_silver1'
  eth1:
    ls: 'ls_lan_silver1'
  eth2:
    ipAllocationType: 'STATIC'
    ipAddress: '20.20.50.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '20.20.50.1'
    ls: 'ls_internet_silver1'
  eth3:
    ipAllocationType: 'STATIC'
    ipAddress: '192.168.12.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '192.168.12.1'
    ls: 'ls_mpls_silver1'
  eth4:
    ls: 'ls_null'
  eth5:
    ls: 'ls_null'
  publickeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQE/9isaw4ToR5GYLm7g6rgLYIZz2c4UdoL4R2DeMypgW1rHv7P0jL3iqR3L+7bY2HggX2DMvdYwXGlKrtoUWY+WhXKiF0tBvH0rWMYR2XZ+s5UiODifkgJ7NEQrOQOwekoHv7l1MmWxI0XVbFYLZ52aMVaQQOljw9SqyMjCAlF2BnXRfSNW86BAF/KiJVhECbvEfrSBH855OGORlXAHtzyTTEpj0zbTHmAzjLKoqTaXjD9IMf38yqDajMa/XwRUKevK+hkvoWCXaKmY+xXy0Csbf4dkNrJBLrEysfRKwKqkxjXJKKBoQ4b+uTGb+x32DPZCphL2ksEx+8oRb/pCKR adeleporte@adeleporte-m01.vmware.com'

vce3:
  instanceid: VCE_SILVER2
  hostname: VCE_SILVER2
  description: VCE_SILVER2
  password: Velocloud123
  image: 'images/edge-VC_VMDK-x86_64-3.2.0-49-R320-20180409-GA-updatable-ext4.ova'
  lat: '40.4167754'
  long: '-3.7037901999999576'
  lan:
    ipAddress: '10.0.2.1'
  eth0:
    ls: 'ls_lan_silver2'
  eth1:
    ls: 'ls_lan_silver2'
  eth2:
    ipAllocationType: 'STATIC'
    ipAddress: '20.20.60.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '20.20.60.1'
    ls: 'ls_internet_silver2'
  eth3:
    ipAllocationType: 'STATIC'
    ipAddress: '192.168.13.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '192.168.13.1'
    ls: 'ls_mpls_silver2'
  eth4:
    ls: 'ls_null'
  eth5:
    ls: 'ls_null'
  publickeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQE/9isaw4ToR5GYLm7g6rgLYIZz2c4UdoL4R2DeMypgW1rHv7P0jL3iqR3L+7bY2HggX2DMvdYwXGlKrtoUWY+WhXKiF0tBvH0rWMYR2XZ+s5UiODifkgJ7NEQrOQOwekoHv7l1MmWxI0XVbFYLZ52aMVaQQOljw9SqyMjCAlF2BnXRfSNW86BAF/KiJVhECbvEfrSBH855OGORlXAHtzyTTEpj0zbTHmAzjLKoqTaXjD9IMf38yqDajMa/XwRUKevK+hkvoWCXaKmY+xXy0Csbf4dkNrJBLrEysfRKwKqkxjXJKKBoQ4b+uTGb+x32DPZCphL2ksEx+8oRb/pCKR adeleporte@adeleporte-m01.vmware.com'

vce4:
  instanceid: VCE_SILVER3
  hostname: VCE_SILVER3
  description: VCE_SILVER3
  password: Velocloud123
  image: 'images/edge-VC_VMDK-x86_64-3.2.0-49-R320-20180409-GA-updatable-ext4.ova'
  lat: '45.4642035'
  long: '9.189981999999986'
  lan:
    ipAddress: '10.0.3.1'
  eth0:
    ls: 'ls_lan_silver3'
  eth1:
    ls: 'ls_lan_silver3'
  eth2:
    ipAllocationType: 'STATIC'
    ipAddress: '20.20.70.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '20.20.70.1'
    ls: 'ls_internet_silver3'
  eth3:
    ipAllocationType: 'STATIC'
    ipAddress: '192.168.14.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '192.168.14.1'
    ls: 'ls_mpls_silver3'
  eth4:
    ls: 'ls_null'
  eth5:
    ls: 'ls_null'
  publickeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQE/9isaw4ToR5GYLm7g6rgLYIZz2c4UdoL4R2DeMypgW1rHv7P0jL3iqR3L+7bY2HggX2DMvdYwXGlKrtoUWY+WhXKiF0tBvH0rWMYR2XZ+s5UiODifkgJ7NEQrOQOwekoHv7l1MmWxI0XVbFYLZ52aMVaQQOljw9SqyMjCAlF2BnXRfSNW86BAF/KiJVhECbvEfrSBH855OGORlXAHtzyTTEpj0zbTHmAzjLKoqTaXjD9IMf38yqDajMa/XwRUKevK+hkvoWCXaKmY+xXy0Csbf4dkNrJBLrEysfRKwKqkxjXJKKBoQ4b+uTGb+x32DPZCphL2ksEx+8oRb/pCKR adeleporte@adeleporte-m01.vmware.com'

vce5:
  instanceid: VCE_DC1
  hostname: VCE_DC1
  description: VCE_DC1
  password: Velocloud123
  image: 'images/edge-VC_VMDK-x86_64-3.2.0-49-R320-20180409-GA-updatable-ext4.ova'
  lat: '48.856614'
  long: '2.3522219000000177'
  lan:
    ipAddress: '10.0.4.1'
  eth0:
    ls: 'ls_lan_dc1'
  eth1:
    ls: 'ls_lan_dc1'
  eth2:
    ipAllocationType: 'STATIC'
    ipAddress: '20.20.80.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '20.20.80.1'
    ls: 'ls_internet_dc1'
  eth3:
    ipAllocationType: 'STATIC'
    ipAddress: '192.168.10.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '192.168.10.1'
    ls: 'ls_mpls_dc1'
  eth4:
    ls: 'ls_null'
  eth5:
    ls: 'ls_null'
  publickeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQE/9isaw4ToR5GYLm7g6rgLYIZz2c4UdoL4R2DeMypgW1rHv7P0jL3iqR3L+7bY2HggX2DMvdYwXGlKrtoUWY+WhXKiF0tBvH0rWMYR2XZ+s5UiODifkgJ7NEQrOQOwekoHv7l1MmWxI0XVbFYLZ52aMVaQQOljw9SqyMjCAlF2BnXRfSNW86BAF/KiJVhECbvEfrSBH855OGORlXAHtzyTTEpj0zbTHmAzjLKoqTaXjD9IMf38yqDajMa/XwRUKevK+hkvoWCXaKmY+xXy0Csbf4dkNrJBLrEysfRKwKqkxjXJKKBoQ4b+uTGb+x32DPZCphL2ksEx+8oRb/pCKR adeleporte@adeleporte-m01.vmware.com'

vce6:
  instanceid: VCE_DC2
  hostname: VCE_DC2
  description: VCE_DC2
  password: Velocloud123
  image: 'images/edge-VC_VMDK-x86_64-3.2.0-49-R320-20180409-GA-updatable-ext4.ova'
  lat: '51.5073509'
  long: '-0.12775829999998223'
  lan:
    ipAddress: '10.0.5.1'
  eth0:
    ls: 'ls_lan_dc2'
  eth1:
    ls: 'ls_lan_dc2'
  eth2:
    ipAllocationType: 'STATIC'
    ipAddress: '20.20.90.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '20.20.90.1'
    ls: 'ls_internet_dc2'
  eth3:
    ipAllocationType: 'STATIC'
    ipAddress: '192.168.11.100'
    subnetMask: '255.255.255.0'
    gatewayAddress: '192.168.11.1'
    ls: 'ls_mpls_dc2'
  eth4:
    ls: 'ls_null'
  eth5:
    ls: 'ls_null'
  publickeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQE/9isaw4ToR5GYLm7g6rgLYIZz2c4UdoL4R2DeMypgW1rHv7P0jL3iqR3L+7bY2HggX2DMvdYwXGlKrtoUWY+WhXKiF0tBvH0rWMYR2XZ+s5UiODifkgJ7NEQrOQOwekoHv7l1MmWxI0XVbFYLZ52aMVaQQOljw9SqyMjCAlF2BnXRfSNW86BAF/KiJVhECbvEfrSBH855OGORlXAHtzyTTEpj0zbTHmAzjLKoqTaXjD9IMf38yqDajMa/XwRUKevK+hkvoWCXaKmY+xXy0Csbf4dkNrJBLrEysfRKwKqkxjXJKKBoQ4b+uTGb+x32DPZCphL2ksEx+8oRb/pCKR adeleporte@adeleporte-m01.vmware.com'

# Client Install
lubuntuOva: 'lubuntu.ova'
clients:
  - { name: 'ls_lan_dc1' }
  - { name: 'ls_lan_dc2' }
  - { name: 'ls_lan_bronze' }
  - { name: 'ls_lan_silver1' }
  - { name: 'ls_lan_silver2' }
  - { name: 'ls_lan_silver3' }
 
