---
- name: Deploy NSX OVA
  hosts: localhost
  gather_facts: False
  vars_files:
    - answerfile-deployLab.yml
  roles:
    - role: deploy-nsx-ova
  tags: nsx_ova

- name: Base NSX Deployment (Install)
  hosts: localhost
  gather_facts: False
  vars_files:
    - answerfile-deployLab.yml
  roles:
    - role: base-config-nsx
  tags: nsx_install

- name: Lab NSX Deployment (Deploy LS and Edges)
  hosts: localhost
  gather_facts: False
  vars_files:
    - answerfile-deployLab.yml
  roles:
    - role: lab-config-nsx
  tags: lab_install
