---
- name: deploy_vco
  vco_deploy_ova:
    ovftool_path: '{{ ovfToolPath }}'
    ova_file: '{{ vco.image }}'
    vcenter: '{{ deployVcIPAddress }}'
    vcenter_user: '{{ deployVcUser }}'
    vcenter_passwd: '{{ deployVcPassword }}'
    datacenter: '{{ deployDataCenterName }}'
    cluster: '{{ deployCluster }}'
    datastore: '{{ deployMgmtDatastoreName }}'
    portgroup: '{{ vco.ls|to_portgroup( nsxmanager_spec, transportZoneName ) }}'
    vmname: '{{ vco.hostname }}'
    instanceid: '{{ vco.instanceid }}'
    hostname: '{{ vco.hostname }}'
    password: '{{ vco.password }}'
    publickeys: '{{ vco.publickeys }}'
    #dns1: '{{ dns1 }}'
    #dns2: '{{ dns2 }}'
    eth0ipAllocationType: '{{ vco.eth0.ipAllocationType }}'
    eth0ipAddress: '{{ vco.eth0.ipAddress }}'
    eth0subnetMask: '{{ vco.eth0.subnetMask }}'
    eth0gatewayAddress: '{{ vco.eth0.gatewayAddress }}'
    userdata: "{{ lookup('template', 'templates/vco-user-data.j2') | b64encode }}"
  register: deploy_vco
